import {
  ArrowLeft,
  ArrowRightLeft,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleArrowRight,
  CircleCheck,
  Eye,
  EyeOff,
  Headset,
  HelpCircle,
  Home,
  Loader2,
  Lock,
  LockKeyholeOpen,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Undo2,
  User,
  X,
  Trash,
} from "lucide-react";

export const Icons = {
  undo2: Undo2,
  chevronRight: ChevronRight,
  eye: Eye,
  eyeOff: EyeOff,
  user: User,
  lockKeyholeOpen: LockKeyholeOpen,
  circleAlert: CircleAlert,
  headset: Headset,
  lock: Lock,
  plus: Plus,
  arrowLeft: ArrowLeft,
  loader2: Loader2,
  save: Save,
  pencil: Pencil,
  moreHorizontal: MoreHorizontal,
  question: HelpCircle,
  circleArrowRight: CircleArrowRight,
  cross: X,
  arrowRightLeft: ArrowRightLeft,
  rotateCcw: RotateCcw,
  x: X,
  chevronLeft: ChevronLeft,
  circleCheck: CircleCheck,
  trash: Trash,
  refreshCw: RefreshCw,
  home: Home,
};
